version: "3.9"

services:
  mysql-db:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - app-network

  backend:
    build: ./server
    container_name: backend
    restart: always
    depends_on:
      mysql-db:
        condition: service_healthy
    env_file:
      - ./server/.env
    ports:
      - "3000:3000"
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:


























# version: "3.9"

# services:
#   mysql-db:
#     image: mysql:8
#     container_name: mysql-db
#     environment:
#       MYSQL_ROOT_PASSWORD: root
#       MYSQL_DATABASE: mydatabase
#     ports:
#       - "3306:3306"
#     # volumes:
#     #   - mysql_data:/var/lib/mysql
#     networks:
#       - app-network
#     healthcheck:
#       test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
#       interval: 10s
#       timeout: 10s
#       retries: 10
#       start_period: 40s

#   backend:
#     build: ./server
#     container_name: backend
#     restart: always
#     ports:
#       - "3000:3000"
#     depends_on:
#       mysql-db:
#         condition: service_healthy
#     env_file:
#       - ./server/.env
#     networks:
#       - app-network

#   frontend:
#     build: ./frontend
#     container_name: frontend
#     restart: always
#     depends_on:
#       - backend
#     ports:
#       - "5000:5000"
#     networks:
#       - app-network

# networks:
#   app-network:
#     driver: bridge

# volumes:
#   mysql_data:

